# Generated by Django 2.1.2 on 2018-10-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='dec_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='decision',
            name='dec_progress',
            field=models.IntegerField(default=0),
        ),
    ]
