# Generated by Django 2.1.2 on 2018-10-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0003_auto_20181016_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decision',
            name='dec_always',
        ),
        migrations.RemoveField(
            model_name='decision',
            name='dec_date',
        ),
        migrations.RemoveField(
            model_name='decision',
            name='dec_dep',
        ),
        migrations.AddField(
            model_name='decision',
            name='dec_term',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
