# Generated by Django 2.1.2 on 2018-10-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0004_auto_20181016_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='order_n',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
