# Generated by Django 2.1.2 on 2018-10-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0006_decision_dec_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='proto_decisions_prefix',
            field=models.CharField(default='РЕШИЛИ: ', max_length=32),
        ),
        migrations.AddField(
            model_name='protocol',
            name='proto_fabula_prefix',
            field=models.CharField(default='СЛУШАЛИ: ', max_length=32),
        ),
        migrations.AddField(
            model_name='protocol',
            name='proto_off',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='decision',
            name='dec_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='decision',
            name='dec_term',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='decision',
            name='dec_type',
            field=models.IntegerField(choices=[(0, 'Пункт'), (1, 'Разделитель')], db_index=True, default=1),
        ),
    ]
