# Generated by Django 2.1.2 on 2018-10-18 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0018_remove_meeting_protocol'),
        ('protocols', '0007_auto_20181018_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.Meeting'),
        ),
    ]
