# Generated by Django 2.1.2 on 2018-10-02 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet_type', models.CharField(choices=[('V', 'Видео конференция'), ('A', 'Аудио селектор'), ('I', 'Очное совещание')], default='I', max_length=1)),
                ('meet_place', models.CharField(db_index=True, max_length=128)),
                ('meet_subj', models.CharField(db_index=True, max_length=128)),
                ('meet_lead', models.CharField(db_index=True, max_length=128)),
                ('meet_date', models.DateField(default=django.utils.timezone.now)),
                ('meet_start', models.TimeField(default=django.utils.timezone.now, null=True)),
                ('meet_end', models.TimeField(default=django.utils.timezone.now, null=True)),
                ('meet_init', models.CharField(db_index=True, max_length=64)),
                ('meet_acc', models.CharField(db_index=True, max_length=64)),
                ('meet_tel', models.CharField(max_length=10)),
                ('meet_attrs', models.CharField(max_length=16)),
            ],
        ),
    ]
