# Generated by Django 2.1.2 on 2018-10-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='dep',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
    ]
