# Generated by Django 2.1.2 on 2018-10-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_init',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='is_lead',
            field=models.IntegerField(default=0),
        ),
    ]
