# Generated by Django 2.1.2 on 2018-10-02 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('tm', models.CharField(db_index=True, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f', models.CharField(db_index=True, max_length=32)),
                ('i', models.CharField(db_index=True, max_length=32)),
                ('o', models.CharField(db_index=True, max_length=32)),
                ('fio', models.CharField(db_index=True, max_length=64)),
                ('dol', models.CharField(db_index=True, max_length=128)),
                ('dep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.Dep')),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio_addr', models.CharField(db_index=True, max_length=256)),
                ('studio_type', models.CharField(choices=[('V', 'Видео'), ('A', 'Аудио')], default='V', max_length=1)),
                ('dep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.Dep')),
            ],
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meet_attrs',
            field=models.CharField(default='                ', max_length=16),
        ),
        migrations.AddField(
            model_name='item',
            name='meet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.Meeting'),
        ),
        migrations.AddField(
            model_name='item',
            name='otv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.Member'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='members',
            field=models.ManyToManyField(to='meetings.Member'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='studios',
            field=models.ManyToManyField(to='meetings.Studio'),
        ),
    ]
