# Generated by Django 2.1.2 on 2018-10-07 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20181007_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting_member',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='meeting_member',
            name='member',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='members',
        ),
        migrations.AddField(
            model_name='member',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.Meeting'),
        ),
        migrations.AddField(
            model_name='member',
            name='order_n',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Meeting_Member',
        ),
    ]
