# Generated by Django 2.1.2 on 2018-10-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20181002_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meet_acc',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meet_attrs',
            field=models.CharField(blank=True, default='                ', max_length=16),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meet_end',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meet_init',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meet_lead',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meet_start',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meet_tel',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='o',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
