# Generated by Django 2.1.2 on 2018-10-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_auto_20181007_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='order_n',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
