# Generated by Django 2.1.2 on 2018-10-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_auto_20181007_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_speaker',
            field=models.IntegerField(default=0),
        ),
    ]
