# Generated by Django 2.1.2 on 2018-10-10 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_auto_20181010_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dep',
            name='name',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.Dep', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dol',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='f',
            field=models.CharField(db_index=True, max_length=32, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='i',
            field=models.CharField(db_index=True, max_length=32, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='o',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Очество'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tel',
            field=models.CharField(max_length=16, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='dep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.Dep', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='studio_addr',
            field=models.CharField(db_index=True, max_length=256, verbose_name='Адрес студии'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='studio_type',
            field=models.CharField(choices=[('V', 'Видео'), ('A', 'Аудио')], default='V', max_length=1, verbose_name='Тип студии'),
        ),
    ]
