# Generated by Django 2.1.2 on 2018-10-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_auto_20181010_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='o',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Отчество'),
        ),
    ]
