# Generated by Django 2.1.2 on 2018-10-07 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_auto_20181007_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meetings.Meeting'),
        ),
    ]
