# Generated by Django 2.1.2 on 2018-10-08 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_auto_20181007_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='item_subj',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='tm',
            new_name='item_time',
        ),
        migrations.RemoveField(
            model_name='item',
            name='meet',
        ),
        migrations.RemoveField(
            model_name='item',
            name='otv',
        ),
        migrations.AddField(
            model_name='item',
            name='dep',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='item',
            name='dol',
            field=models.CharField(db_index=True, default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='f',
            field=models.CharField(db_index=True, default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='fio',
            field=models.CharField(db_index=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='i',
            field=models.CharField(db_index=True, default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meetings.Meeting'),
        ),
        migrations.AddField(
            model_name='item',
            name='o',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='item',
            name='order_n',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
