# Generated by Django 2.1.2 on 2018-10-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_auto_20181010_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tel',
            field=models.CharField(blank=True, max_length=16, verbose_name='Телефон'),
        ),
    ]
