# Generated by Django 2.1.2 on 2018-10-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_auto_20181010_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1_4', models.IntegerField(default=0)),
                ('p2_4', models.IntegerField(default=0)),
                ('p3_4', models.IntegerField(default=0)),
                ('p4_4', models.IntegerField(default=0)),
                ('p5_1', models.IntegerField(default=0)),
                ('p5_2', models.IntegerField(default=0)),
                ('p5_3', models.IntegerField(default=0)),
                ('p5_4', models.IntegerField(default=0)),
                ('p6_2', models.IntegerField(default=0)),
                ('p6_4', models.IntegerField(default=0)),
                ('p7_4', models.IntegerField(default=0)),
                ('p8_4', models.IntegerField(default=0)),
                ('p9_1', models.IntegerField(default=0)),
                ('p9_4', models.IntegerField(default=0)),
                ('p10_4', models.IntegerField(default=0)),
                ('p11_4', models.IntegerField(default=0)),
            ],
        ),
    ]
