# Generated by Django 2.1.2 on 2018-10-08 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_remove_item_fio'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_n', models.PositiveIntegerField(default=0)),
                ('meeting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meetings.Meeting')),
                ('studio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meetings.Studio')),
            ],
        ),
    ]
