# Generated by Django 2.1.2 on 2018-10-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0009_check_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='meeting',
        ),
        migrations.AddField(
            model_name='meeting',
            name='p10_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meeting',
            name='p11_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meeting',
            name='p1_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meeting',
            name='p2_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meeting',
            name='p3_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meeting',
            name='p4_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meeting',
            name='p5_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meeting',
            name='p5_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meeting',
            name='p5_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meeting',
            name='p5_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meeting',
            name='p6_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meeting',
            name='p6_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meeting',
            name='p7_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meeting',
            name='p8_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meeting',
            name='p9_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meeting',
            name='p9_4',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Check',
        ),
    ]
