# Generated by Django 2.1.2 on 2018-10-11 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0010_auto_20181011_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1_4', models.IntegerField(default=0)),
                ('p2_4', models.IntegerField(default=0)),
                ('p3_4', models.IntegerField(default=0)),
                ('p4_4', models.IntegerField(default=0)),
                ('p5_1', models.IntegerField(default=0)),
                ('p5_2', models.IntegerField(default=0)),
                ('p5_3', models.IntegerField(default=0)),
                ('p5_4', models.IntegerField(default=0)),
                ('p6_2', models.IntegerField(default=0)),
                ('p6_4', models.IntegerField(default=0)),
                ('p7_4', models.IntegerField(default=0)),
                ('p8_4', models.IntegerField(default=0)),
                ('p9_1', models.IntegerField(default=0)),
                ('p9_4', models.IntegerField(default=0)),
                ('p10_4', models.IntegerField(default=0)),
                ('p11_4', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='p10_4',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='p11_4',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='p1_4',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='p2_4',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='p3_4',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='p4_4',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='p5_1',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='p5_2',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='p5_3',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='p5_4',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='p6_2',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='p6_4',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='p7_4',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='p8_4',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='p9_1',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='p9_4',
        ),
        migrations.AddField(
            model_name='check',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meetings.Meeting'),
        ),
    ]
