# Generated by Django 2.1.2 on 2018-10-11 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0011_auto_20181011_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='meeting',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='meetings.Meeting'),
            preserve_default=False,
        ),
    ]
