# Generated by Django 2.1.2 on 2018-10-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0012_auto_20181011_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='p10_4',
        ),
        migrations.RemoveField(
            model_name='check',
            name='p11_4',
        ),
        migrations.RemoveField(
            model_name='check',
            name='p1_4',
        ),
        migrations.RemoveField(
            model_name='check',
            name='p2_4',
        ),
        migrations.RemoveField(
            model_name='check',
            name='p3_4',
        ),
        migrations.RemoveField(
            model_name='check',
            name='p4_4',
        ),
        migrations.RemoveField(
            model_name='check',
            name='p5_1',
        ),
        migrations.RemoveField(
            model_name='check',
            name='p5_2',
        ),
        migrations.RemoveField(
            model_name='check',
            name='p5_3',
        ),
        migrations.RemoveField(
            model_name='check',
            name='p5_4',
        ),
        migrations.RemoveField(
            model_name='check',
            name='p6_2',
        ),
        migrations.RemoveField(
            model_name='check',
            name='p6_4',
        ),
        migrations.RemoveField(
            model_name='check',
            name='p7_4',
        ),
        migrations.RemoveField(
            model_name='check',
            name='p8_4',
        ),
        migrations.RemoveField(
            model_name='check',
            name='p9_1',
        ),
        migrations.RemoveField(
            model_name='check',
            name='p9_4',
        ),
        migrations.AddField(
            model_name='check',
            name='complete',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='check',
            name='data',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='check',
            name='total',
            field=models.IntegerField(default=1),
        ),
    ]
