# Generated by Django 2.1.2 on 2018-10-12 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0013_auto_20181012_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='meeting',
        ),
        migrations.DeleteModel(
            name='Check',
        ),
    ]
