# Generated by Django 2.1.2 on 2018-10-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0015_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_presence',
            field=models.IntegerField(default=0),
        ),
    ]
