# Generated by Django 2.1.2 on 2018-10-18 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0007_auto_20181018_0937'),
        ('meetings', '0016_member_is_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='protocol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='protocols.Protocol'),
        ),
    ]
