# Generated by Django 2.1.2 on 2018-10-18 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0017_meeting_protocol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='protocol',
        ),
    ]
